// Package store owns core.db: connection settings, migrations and queries.
// Only the core service opens this database.
package store

import (
	"context"
	"database/sql"
	"embed"
	"fmt"
	"io/fs"
	"log/slog"
	"sort"
	"strconv"
	"strings"
	"time"

	_ "modernc.org/sqlite" // registers the "sqlite" driver

	"marquee/internal/store/db"
)

//go:embed migrations/*.sql
var migrationFiles embed.FS

// Store wraps the core database. Queries are generated by sqlc from
// internal/store/queries (see sqlc.yaml); this package maps them to
// catalog types.
type Store struct {
	db  *sql.DB
	log *slog.Logger // non-nil when query logging is enabled
	q   *db.Queries
}

// Option configures a Store.
type Option func(*Store)

// WithQueryLog logs every query (name, duration, error) at debug level.
func WithQueryLog(log *slog.Logger) Option {
	return func(s *Store) { s.log = log }
}

// Open opens (creating if needed) the database at path and applies pending
// migrations. Use ":memory:" for a private in-memory database.
func Open(ctx context.Context, path string, opts ...Option) (*Store, error) {
	pragmas := "_pragma=foreign_keys(1)&_pragma=busy_timeout(5000)&_pragma=synchronous(NORMAL)"
	dsn := "file:" + path + "?" + pragmas
	if path != ":memory:" {
		dsn += "&_pragma=journal_mode(WAL)"
	}
	conn, err := sql.Open("sqlite", dsn)
	if err != nil {
		return nil, err
	}
	// One connection serializes writes; SQLite allows a single writer anyway.
	conn.SetMaxOpenConns(1)
	if err := conn.PingContext(ctx); err != nil {
		conn.Close()
		return nil, fmt.Errorf("open %s: %w", path, err)
	}
	s := &Store{db: conn}
	for _, opt := range opts {
		opt(s)
	}
	s.q = db.New(s.wrap(conn))
	if err := s.migrate(ctx); err != nil {
		conn.Close()
		return nil, err
	}
	return s, nil
}

// inTx runs fn with queries bound to a transaction, committing on success.
func (s *Store) inTx(ctx context.Context, fn func(q *db.Queries) error) error {
	tx, err := s.db.BeginTx(ctx, nil)
	if err != nil {
		return err
	}
	defer tx.Rollback()
	if err := fn(db.New(s.wrap(tx))); err != nil {
		return err
	}
	return tx.Commit()
}

// wrap adds query logging when enabled.
func (s *Store) wrap(conn db.DBTX) db.DBTX {
	if s.log == nil {
		return conn
	}
	return loggedDB{inner: conn, log: s.log}
}

// Close closes the database.
func (s *Store) Close() error { return s.db.Close() }

// SchemaVersion returns the highest applied migration version.
func (s *Store) SchemaVersion(ctx context.Context) (int, error) {
	var v sql.NullInt64
	err := s.db.QueryRowContext(ctx, `SELECT max(version) FROM schema_migrations`).Scan(&v)
	return int(v.Int64), err
}

func (s *Store) migrate(ctx context.Context) error {
	if _, err := s.db.ExecContext(ctx, `CREATE TABLE IF NOT EXISTS schema_migrations (
		version    INTEGER PRIMARY KEY,
		name       TEXT NOT NULL,
		applied_at INTEGER NOT NULL
	) STRICT`); err != nil {
		return fmt.Errorf("create schema_migrations: %w", err)
	}

	entries, err := fs.ReadDir(migrationFiles, "migrations")
	if err != nil {
		return err
	}
	sort.Slice(entries, func(i, j int) bool { return entries[i].Name() < entries[j].Name() })

	for _, e := range entries {
		name := e.Name()
		version, err := strconv.Atoi(strings.SplitN(name, "_", 2)[0])
		if err != nil {
			return fmt.Errorf("migration %s: name must start with a number", name)
		}
		var applied int
		if err := s.db.QueryRowContext(ctx, `SELECT count(*) FROM schema_migrations WHERE version = ?`, version).Scan(&applied); err != nil {
			return err
		}
		if applied > 0 {
			continue
		}
		body, err := migrationFiles.ReadFile("migrations/" + name)
		if err != nil {
			return err
		}
		tx, err := s.db.BeginTx(ctx, nil)
		if err != nil {
			return err
		}
		if _, err := tx.ExecContext(ctx, string(body)); err != nil {
			tx.Rollback()
			return fmt.Errorf("migration %s: %w", name, err)
		}
		if _, err := tx.ExecContext(ctx, `INSERT INTO schema_migrations (version, name, applied_at) VALUES (?, ?, ?)`,
			version, name, time.Now().UnixMilli()); err != nil {
			tx.Rollback()
			return err
		}
		if err := tx.Commit(); err != nil {
			return err
		}
	}
	return nil
}
