// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: catalog.sql

package db

import (
	"context"
)

const getSeasonEpisodesFetchedAt = `-- name: GetSeasonEpisodesFetchedAt :one
SELECT se.episodes_fetched_at
FROM seasons se
JOIN titles t ON t.id = se.title_id
WHERE t.ref = ? AND se.season_number = ?
`

type GetSeasonEpisodesFetchedAtParams struct {
	Ref          string
	SeasonNumber int64
}

func (q *Queries) GetSeasonEpisodesFetchedAt(ctx context.Context, arg GetSeasonEpisodesFetchedAtParams) (*int64, error) {
	row := q.db.QueryRowContext(ctx, getSeasonEpisodesFetchedAt, arg.Ref, arg.SeasonNumber)
	var episodes_fetched_at *int64
	err := row.Scan(&episodes_fetched_at)
	return episodes_fetched_at, err
}

const getTitleByRef = `-- name: GetTitleByRef :one
SELECT id, ref, kind, source, tmdb_id, tvmaze_id, tvdb_id, imdb_id, name, original_name, year, overview, status, runtime_min, genres, poster_url, fetched_at, details FROM titles WHERE ref = ?
`

func (q *Queries) GetTitleByRef(ctx context.Context, ref string) (Title, error) {
	row := q.db.QueryRowContext(ctx, getTitleByRef, ref)
	var i Title
	err := row.Scan(
		&i.ID,
		&i.Ref,
		&i.Kind,
		&i.Source,
		&i.TmdbID,
		&i.TvmazeID,
		&i.TvdbID,
		&i.ImdbID,
		&i.Name,
		&i.OriginalName,
		&i.Year,
		&i.Overview,
		&i.Status,
		&i.RuntimeMin,
		&i.Genres,
		&i.PosterUrl,
		&i.FetchedAt,
		&i.Details,
	)
	return i, err
}

const getTitleIDByRef = `-- name: GetTitleIDByRef :one
SELECT id FROM titles WHERE ref = ?
`

func (q *Queries) GetTitleIDByRef(ctx context.Context, ref string) (string, error) {
	row := q.db.QueryRowContext(ctx, getTitleIDByRef, ref)
	var id string
	err := row.Scan(&id)
	return id, err
}

const listEpisodes = `-- name: ListEpisodes :many
SELECT i.ref, i.season_number, i.episode_number, i.name, i.overview,
       i.air_date, i.runtime_min, i.rating
FROM items i
JOIN titles t ON t.id = i.title_id
WHERE t.ref = ? AND i.kind = 'episode' AND i.season_number = ?
ORDER BY i.episode_number
`

type ListEpisodesParams struct {
	Ref          string
	SeasonNumber *int64
}

type ListEpisodesRow struct {
	Ref           string
	SeasonNumber  *int64
	EpisodeNumber *int64
	Name          *string
	Overview      *string
	AirDate       *string
	RuntimeMin    *int64
	Rating        *float64
}

func (q *Queries) ListEpisodes(ctx context.Context, arg ListEpisodesParams) ([]ListEpisodesRow, error) {
	rows, err := q.db.QueryContext(ctx, listEpisodes, arg.Ref, arg.SeasonNumber)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEpisodesRow{}
	for rows.Next() {
		var i ListEpisodesRow
		if err := rows.Scan(
			&i.Ref,
			&i.SeasonNumber,
			&i.EpisodeNumber,
			&i.Name,
			&i.Overview,
			&i.AirDate,
			&i.RuntimeMin,
			&i.Rating,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSeasons = `-- name: ListSeasons :many
SELECT season_number, name, air_date, episode_count
FROM seasons
WHERE title_id = ?
ORDER BY season_number
`

type ListSeasonsRow struct {
	SeasonNumber int64
	Name         *string
	AirDate      *string
	EpisodeCount *int64
}

func (q *Queries) ListSeasons(ctx context.Context, titleID string) ([]ListSeasonsRow, error) {
	rows, err := q.db.QueryContext(ctx, listSeasons, titleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSeasonsRow{}
	for rows.Next() {
		var i ListSeasonsRow
		if err := rows.Scan(
			&i.SeasonNumber,
			&i.Name,
			&i.AirDate,
			&i.EpisodeCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markSeasonEpisodesFetched = `-- name: MarkSeasonEpisodesFetched :exec
INSERT INTO seasons (title_id, season_number, episode_count, episodes_fetched_at)
VALUES (?, ?, ?, ?)
ON CONFLICT (title_id, season_number) DO UPDATE SET
  episodes_fetched_at = excluded.episodes_fetched_at
`

type MarkSeasonEpisodesFetchedParams struct {
	TitleID           string
	SeasonNumber      int64
	EpisodeCount      *int64
	EpisodesFetchedAt *int64
}

// Records when a season's episodes were fetched (creates the season row if needed).
func (q *Queries) MarkSeasonEpisodesFetched(ctx context.Context, arg MarkSeasonEpisodesFetchedParams) error {
	_, err := q.db.ExecContext(ctx, markSeasonEpisodesFetched,
		arg.TitleID,
		arg.SeasonNumber,
		arg.EpisodeCount,
		arg.EpisodesFetchedAt,
	)
	return err
}

const upsertEpisode = `-- name: UpsertEpisode :exec
INSERT INTO items (
  id, title_id, kind, season_number, episode_number,
  name, overview, air_date, runtime_min, rating, ref
) VALUES (
  ?, ?, 'episode', ?, ?,
  ?, ?, ?, ?, ?, ?
)
ON CONFLICT (ref) DO UPDATE SET
  name        = excluded.name,
  overview    = excluded.overview,
  air_date    = excluded.air_date,
  runtime_min = excluded.runtime_min,
  rating      = excluded.rating
`

type UpsertEpisodeParams struct {
	ID            string
	TitleID       string
	SeasonNumber  *int64
	EpisodeNumber *int64
	Name          *string
	Overview      *string
	AirDate       *string
	RuntimeMin    *int64
	Rating        *float64
	Ref           string
}

func (q *Queries) UpsertEpisode(ctx context.Context, arg UpsertEpisodeParams) error {
	_, err := q.db.ExecContext(ctx, upsertEpisode,
		arg.ID,
		arg.TitleID,
		arg.SeasonNumber,
		arg.EpisodeNumber,
		arg.Name,
		arg.Overview,
		arg.AirDate,
		arg.RuntimeMin,
		arg.Rating,
		arg.Ref,
	)
	return err
}

const upsertMovieItem = `-- name: UpsertMovieItem :exec
INSERT INTO items (id, title_id, kind, name, overview, runtime_min, ref)
VALUES (?, ?, 'movie', ?, ?, ?, ?)
ON CONFLICT (ref) DO UPDATE SET
  name        = excluded.name,
  overview    = excluded.overview,
  runtime_min = excluded.runtime_min
`

type UpsertMovieItemParams struct {
	ID         string
	TitleID    string
	Name       *string
	Overview   *string
	RuntimeMin *int64
	Ref        string
}

func (q *Queries) UpsertMovieItem(ctx context.Context, arg UpsertMovieItemParams) error {
	_, err := q.db.ExecContext(ctx, upsertMovieItem,
		arg.ID,
		arg.TitleID,
		arg.Name,
		arg.Overview,
		arg.RuntimeMin,
		arg.Ref,
	)
	return err
}

const upsertSeason = `-- name: UpsertSeason :exec
INSERT INTO seasons (title_id, season_number, name, air_date, episode_count)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT (title_id, season_number) DO UPDATE SET
  name          = excluded.name,
  air_date      = excluded.air_date,
  episode_count = excluded.episode_count
`

type UpsertSeasonParams struct {
	TitleID      string
	SeasonNumber int64
	Name         *string
	AirDate      *string
	EpisodeCount *int64
}

func (q *Queries) UpsertSeason(ctx context.Context, arg UpsertSeasonParams) error {
	_, err := q.db.ExecContext(ctx, upsertSeason,
		arg.TitleID,
		arg.SeasonNumber,
		arg.Name,
		arg.AirDate,
		arg.EpisodeCount,
	)
	return err
}

const upsertTitle = `-- name: UpsertTitle :one

INSERT INTO titles (
  id, ref, kind, source, tmdb_id, tvmaze_id, tvdb_id, imdb_id,
  name, original_name, year, overview, status, runtime_min,
  genres, poster_url, details, fetched_at
) VALUES (
  ?, ?, ?, ?, ?, ?, ?, ?,
  ?, ?, ?, ?, ?, ?,
  ?, ?, ?, ?
)
ON CONFLICT (ref) DO UPDATE SET
  kind          = excluded.kind,
  source        = excluded.source,
  tmdb_id       = excluded.tmdb_id,
  tvmaze_id     = excluded.tvmaze_id,
  tvdb_id       = excluded.tvdb_id,
  imdb_id       = excluded.imdb_id,
  name          = excluded.name,
  original_name = excluded.original_name,
  year          = excluded.year,
  overview      = excluded.overview,
  status        = excluded.status,
  runtime_min   = excluded.runtime_min,
  genres        = excluded.genres,
  poster_url    = excluded.poster_url,
  details       = excluded.details,
  fetched_at    = excluded.fetched_at
RETURNING id
`

type UpsertTitleParams struct {
	ID           string
	Ref          string
	Kind         string
	Source       string
	TmdbID       *int64
	TvmazeID     *int64
	TvdbID       *int64
	ImdbID       *string
	Name         string
	OriginalName *string
	Year         *int64
	Overview     *string
	Status       *string
	RuntimeMin   *int64
	Genres       string
	PosterUrl    *string
	Details      string
	FetchedAt    int64
}

// Catalog queries: titles, seasons and playable items.
// Each query is named for the generated Go method. Paste any of them into a
// SQLite shell against core.db to debug (replace ? with values).
// Inserts a title or updates it in place, keeping its id. Returns the id.
func (q *Queries) UpsertTitle(ctx context.Context, arg UpsertTitleParams) (string, error) {
	row := q.db.QueryRowContext(ctx, upsertTitle,
		arg.ID,
		arg.Ref,
		arg.Kind,
		arg.Source,
		arg.TmdbID,
		arg.TvmazeID,
		arg.TvdbID,
		arg.ImdbID,
		arg.Name,
		arg.OriginalName,
		arg.Year,
		arg.Overview,
		arg.Status,
		arg.RuntimeMin,
		arg.Genres,
		arg.PosterUrl,
		arg.Details,
		arg.FetchedAt,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}
