// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: downloads.sql

package db

import (
	"context"
)

const completeDownload = `-- name: CompleteDownload :exec
UPDATE downloads SET state = 'completed', error = NULL, bytes_done = bytes_total,
  completed_at = ?, updated_at = ? WHERE id = ?
`

type CompleteDownloadParams struct {
	CompletedAt *int64
	UpdatedAt   int64
	ID          string
}

func (q *Queries) CompleteDownload(ctx context.Context, arg CompleteDownloadParams) error {
	_, err := q.db.ExecContext(ctx, completeDownload, arg.CompletedAt, arg.UpdatedAt, arg.ID)
	return err
}

const deleteDownloadFiles = `-- name: DeleteDownloadFiles :exec
DELETE FROM download_files WHERE download_id = ?
`

func (q *Queries) DeleteDownloadFiles(ctx context.Context, downloadID string) error {
	_, err := q.db.ExecContext(ctx, deleteDownloadFiles, downloadID)
	return err
}

const getDownload = `-- name: GetDownload :one
SELECT id, title_ref, target_key, scope, season, episode, release_id, "release", name, info_hash, state, audio, subtitles, bytes_done, bytes_total, error, created_at, updated_at, completed_at FROM downloads WHERE id = ?
`

func (q *Queries) GetDownload(ctx context.Context, id string) (Download, error) {
	row := q.db.QueryRowContext(ctx, getDownload, id)
	var i Download
	err := row.Scan(
		&i.ID,
		&i.TitleRef,
		&i.TargetKey,
		&i.Scope,
		&i.Season,
		&i.Episode,
		&i.ReleaseID,
		&i.Release,
		&i.Name,
		&i.InfoHash,
		&i.State,
		&i.Audio,
		&i.Subtitles,
		&i.BytesDone,
		&i.BytesTotal,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const insertDownload = `-- name: InsertDownload :exec

INSERT INTO downloads (
  id, title_ref, target_key, scope, season, episode, release_id, release, name,
  info_hash, state, audio, subtitles, created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertDownloadParams struct {
	ID        string
	TitleRef  string
	TargetKey string
	Scope     string
	Season    *int64
	Episode   *int64
	ReleaseID string
	Release   string
	Name      string
	InfoHash  *string
	State     string
	Audio     string
	Subtitles string
	CreatedAt int64
	UpdatedAt int64
}

// Downloads and the files chosen from each torrent.
func (q *Queries) InsertDownload(ctx context.Context, arg InsertDownloadParams) error {
	_, err := q.db.ExecContext(ctx, insertDownload,
		arg.ID,
		arg.TitleRef,
		arg.TargetKey,
		arg.Scope,
		arg.Season,
		arg.Episode,
		arg.ReleaseID,
		arg.Release,
		arg.Name,
		arg.InfoHash,
		arg.State,
		arg.Audio,
		arg.Subtitles,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const insertDownloadFile = `-- name: InsertDownloadFile :exec
INSERT INTO download_files (
  download_id, file_index, path, size_bytes, kind, language, item_ref, selected
) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertDownloadFileParams struct {
	DownloadID string
	FileIndex  int64
	Path       string
	SizeBytes  int64
	Kind       string
	Language   *string
	ItemRef    *string
	Selected   int64
}

func (q *Queries) InsertDownloadFile(ctx context.Context, arg InsertDownloadFileParams) error {
	_, err := q.db.ExecContext(ctx, insertDownloadFile,
		arg.DownloadID,
		arg.FileIndex,
		arg.Path,
		arg.SizeBytes,
		arg.Kind,
		arg.Language,
		arg.ItemRef,
		arg.Selected,
	)
	return err
}

const listDownloadFiles = `-- name: ListDownloadFiles :many
SELECT download_id, file_index, path, size_bytes, kind, language, item_ref, selected, bytes_done, library_path FROM download_files WHERE download_id = ? ORDER BY file_index
`

func (q *Queries) ListDownloadFiles(ctx context.Context, downloadID string) ([]DownloadFile, error) {
	rows, err := q.db.QueryContext(ctx, listDownloadFiles, downloadID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DownloadFile{}
	for rows.Next() {
		var i DownloadFile
		if err := rows.Scan(
			&i.DownloadID,
			&i.FileIndex,
			&i.Path,
			&i.SizeBytes,
			&i.Kind,
			&i.Language,
			&i.ItemRef,
			&i.Selected,
			&i.BytesDone,
			&i.LibraryPath,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDownloads = `-- name: ListDownloads :many
SELECT id, title_ref, target_key, scope, season, episode, release_id, "release", name, info_hash, state, audio, subtitles, bytes_done, bytes_total, error, created_at, updated_at, completed_at FROM downloads ORDER BY created_at DESC LIMIT ?
`

func (q *Queries) ListDownloads(ctx context.Context, limit int64) ([]Download, error) {
	rows, err := q.db.QueryContext(ctx, listDownloads, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Download{}
	for rows.Next() {
		var i Download
		if err := rows.Scan(
			&i.ID,
			&i.TitleRef,
			&i.TargetKey,
			&i.Scope,
			&i.Season,
			&i.Episode,
			&i.ReleaseID,
			&i.Release,
			&i.Name,
			&i.InfoHash,
			&i.State,
			&i.Audio,
			&i.Subtitles,
			&i.BytesDone,
			&i.BytesTotal,
			&i.Error,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnfinishedDownloads = `-- name: ListUnfinishedDownloads :many
SELECT id, title_ref, target_key, scope, season, episode, release_id, "release", name, info_hash, state, audio, subtitles, bytes_done, bytes_total, error, created_at, updated_at, completed_at FROM downloads
WHERE state IN ('queued', 'metadata', 'downloading', 'paused', 'finalizing')
ORDER BY created_at
`

// Downloads to resume when the core starts.
func (q *Queries) ListUnfinishedDownloads(ctx context.Context) ([]Download, error) {
	rows, err := q.db.QueryContext(ctx, listUnfinishedDownloads)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Download{}
	for rows.Next() {
		var i Download
		if err := rows.Scan(
			&i.ID,
			&i.TitleRef,
			&i.TargetKey,
			&i.Scope,
			&i.Season,
			&i.Episode,
			&i.ReleaseID,
			&i.Release,
			&i.Name,
			&i.InfoHash,
			&i.State,
			&i.Audio,
			&i.Subtitles,
			&i.BytesDone,
			&i.BytesTotal,
			&i.Error,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setDownloadFileLibraryPath = `-- name: SetDownloadFileLibraryPath :exec
UPDATE download_files SET library_path = ?, bytes_done = size_bytes WHERE download_id = ? AND file_index = ?
`

type SetDownloadFileLibraryPathParams struct {
	LibraryPath *string
	DownloadID  string
	FileIndex   int64
}

func (q *Queries) SetDownloadFileLibraryPath(ctx context.Context, arg SetDownloadFileLibraryPathParams) error {
	_, err := q.db.ExecContext(ctx, setDownloadFileLibraryPath, arg.LibraryPath, arg.DownloadID, arg.FileIndex)
	return err
}

const setDownloadFileProgress = `-- name: SetDownloadFileProgress :exec
UPDATE download_files SET bytes_done = ? WHERE download_id = ? AND file_index = ?
`

type SetDownloadFileProgressParams struct {
	BytesDone  int64
	DownloadID string
	FileIndex  int64
}

func (q *Queries) SetDownloadFileProgress(ctx context.Context, arg SetDownloadFileProgressParams) error {
	_, err := q.db.ExecContext(ctx, setDownloadFileProgress, arg.BytesDone, arg.DownloadID, arg.FileIndex)
	return err
}

const setDownloadInfo = `-- name: SetDownloadInfo :exec
UPDATE downloads SET info_hash = ?, name = ?, bytes_total = ?, updated_at = ? WHERE id = ?
`

type SetDownloadInfoParams struct {
	InfoHash   *string
	Name       string
	BytesTotal int64
	UpdatedAt  int64
	ID         string
}

// Called once the torrent metadata is known.
func (q *Queries) SetDownloadInfo(ctx context.Context, arg SetDownloadInfoParams) error {
	_, err := q.db.ExecContext(ctx, setDownloadInfo,
		arg.InfoHash,
		arg.Name,
		arg.BytesTotal,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const setDownloadProgress = `-- name: SetDownloadProgress :exec
UPDATE downloads SET bytes_done = ?, bytes_total = ?, updated_at = ? WHERE id = ?
`

type SetDownloadProgressParams struct {
	BytesDone  int64
	BytesTotal int64
	UpdatedAt  int64
	ID         string
}

func (q *Queries) SetDownloadProgress(ctx context.Context, arg SetDownloadProgressParams) error {
	_, err := q.db.ExecContext(ctx, setDownloadProgress,
		arg.BytesDone,
		arg.BytesTotal,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const setDownloadState = `-- name: SetDownloadState :exec
UPDATE downloads SET state = ?, error = ?, updated_at = ? WHERE id = ?
`

type SetDownloadStateParams struct {
	State     string
	Error     *string
	UpdatedAt int64
	ID        string
}

func (q *Queries) SetDownloadState(ctx context.Context, arg SetDownloadStateParams) error {
	_, err := q.db.ExecContext(ctx, setDownloadState,
		arg.State,
		arg.Error,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
