// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

type Item struct {
	ID            string
	TitleID       string
	Kind          string
	SeasonNumber  *int64
	EpisodeNumber *int64
	Name          *string
	Overview      *string
	AirDate       *string
	RuntimeMin    *int64
	Ref           string
	Rating        *float64
}

type Season struct {
	TitleID           string
	SeasonNumber      int64
	Name              *string
	AirDate           *string
	EpisodeCount      *int64
	EpisodesFetchedAt *int64
}

type Title struct {
	ID           string
	Ref          string
	Kind         string
	Source       string
	TmdbID       *int64
	TvmazeID     *int64
	TvdbID       *int64
	ImdbID       *string
	Name         string
	OriginalName *string
	Year         *int64
	Overview     *string
	Status       *string
	RuntimeMin   *int64
	Genres       string
	PosterUrl    *string
	FetchedAt    int64
	Details      string
}
