// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: releases.sql

package db

import (
	"context"
)

const deleteReleaseCandidates = `-- name: DeleteReleaseCandidates :exec

DELETE FROM release_candidates WHERE target_key = ?
`

// Release candidates found by release searches.
func (q *Queries) DeleteReleaseCandidates(ctx context.Context, targetKey string) error {
	_, err := q.db.ExecContext(ctx, deleteReleaseCandidates, targetKey)
	return err
}

const getReleaseCandidate = `-- name: GetReleaseCandidate :one
SELECT data FROM release_candidates WHERE id = ? ORDER BY fetched_at DESC LIMIT 1
`

// A release may be cached under several searches; the newest copy wins.
func (q *Queries) GetReleaseCandidate(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRowContext(ctx, getReleaseCandidate, id)
	var data string
	err := row.Scan(&data)
	return data, err
}

const insertReleaseCandidate = `-- name: InsertReleaseCandidate :exec
INSERT INTO release_candidates (
  id, target_key, source, name, info_hash, score, seeders, size_bytes, data, fetched_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertReleaseCandidateParams struct {
	ID        string
	TargetKey string
	Source    string
	Name      string
	InfoHash  *string
	Score     int64
	Seeders   int64
	SizeBytes *int64
	Data      string
	FetchedAt int64
}

func (q *Queries) InsertReleaseCandidate(ctx context.Context, arg InsertReleaseCandidateParams) error {
	_, err := q.db.ExecContext(ctx, insertReleaseCandidate,
		arg.ID,
		arg.TargetKey,
		arg.Source,
		arg.Name,
		arg.InfoHash,
		arg.Score,
		arg.Seeders,
		arg.SizeBytes,
		arg.Data,
		arg.FetchedAt,
	)
	return err
}

const listReleaseCandidates = `-- name: ListReleaseCandidates :many
SELECT data, fetched_at
FROM release_candidates
WHERE target_key = ?
ORDER BY score DESC, seeders DESC
`

type ListReleaseCandidatesRow struct {
	Data      string
	FetchedAt int64
}

func (q *Queries) ListReleaseCandidates(ctx context.Context, targetKey string) ([]ListReleaseCandidatesRow, error) {
	rows, err := q.db.QueryContext(ctx, listReleaseCandidates, targetKey)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListReleaseCandidatesRow{}
	for rows.Next() {
		var i ListReleaseCandidatesRow
		if err := rows.Scan(&i.Data, &i.FetchedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
